### ISSUE TITLE
Move to official plugins?

### ISSUE THREAD

**Issue by dLobatog** [theforeman/smart_proxy_vault#1]
Hi there, I just discovered this plugin. It looks neat, and the documentation is pretty good :smile_cat: 

I was wondering if you wanted to move it to @theforeman organization here on GitHub and make it an official plugin. That way you'd get these things for free:

* Tests on our Jenkins CI - which test a matrix of different foreman/ruby versions to ensure the proxy works in different environments
* We can give you some space on the website to list your plugin and link to docs http://www.theforeman.org/plugins/
* RPM / deb packaging 
* More visibility

Let me know if that sounds good to you

**Comment by Ginja** [comment]
Thanks, @dLobatog! That sounds great. Will I still have the ability to push/merge changes?

**Comment by dLobatog** [comment]
Yeah, you'd have admin rights over the repo so you'd basically own the repo. You should have gotten an email with an invitation to the team, once you accept it you can [transfer the repo](https://help.github.com/articles/transferring-a-repository/). After it's transferred, I'll start working on the rpms/debs , installer support...

I made a subteam for Vault related stuff - https://github.com/orgs/theforeman/teams/vault , you may add other maintainers of the plugin if you want.

**Comment by Ginja** [comment]
Great, thanks. It's been transferred. Let me know if you need anything else.

**Comment by Ginja** [comment]
@dLobatog Could the Vault team get read/write privileges on this repo? I think it's read-only right now.

**Comment by domcleal** [comment]
You should have write access now, sorry about that!

**Comment by Ginja** [comment]
Thanks! And no problem. 

Closing this issue.
